go_import_path: code.ysitd.cloud/auth/totp

sudo: false
language: go

cache:
  directories:
    - $GOPATH/pkg/dep/sources

go:
  - 1.10.1
  - 1.10.2

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v -vendor-only

script:
  - go vet -v ./...
  - go test -v ./...
